version: "3.8"
services:
  cassandra:
    image: cassandra:3.11.8
    expose:
      - 9042

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  producer:
    build: ./producer
    environment:
      BROKER_URL: kafka:9092
      WEATHER_API_TOKEN: 108c21bcec86f96bec1cb492eb028586
    depends_on:
      - kafka

  sparkstreaming:
    build: ./sparkstreaming
    environment:
      BROKER_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      CASSANDRA_HOST: cassandra
    depends_on:
      - cassandra
      - kafka

  app:
    build: ./app
    ports:
      - "8001:8001"
    depends_on:
      - kafka
